# Generated by Django 2.1.2 on 2018-10-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
