# Generated by Django 2.1.2 on 2018-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0002_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodtable',
            name='blankets',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='floodtable',
            name='bloodBank',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='floodtable',
            name='sBags',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='floodtable',
            name='transport',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
