# Generated by Django 2.1.2 on 2018-10-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0003_auto_20181013_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodtable',
            name='blankets',
        ),
        migrations.RemoveField(
            model_name='floodtable',
            name='bloodBank',
        ),
        migrations.RemoveField(
            model_name='floodtable',
            name='sBags',
        ),
        migrations.RemoveField(
            model_name='floodtable',
            name='transport',
        ),
    ]
