# Generated by Django 2.1.2 on 2018-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0007_auto_20181013_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rescuetable',
            name='lattitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rescuetable',
            name='longitude',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
