# Generated by Django 2.1.2 on 2018-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0008_auto_20181013_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuetable',
            name='lattitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rescuetable',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
