# Generated by Django 2.1.2 on 2018-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0010_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('orgName', models.CharField(max_length=30)),
                ('rescueHome', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=13)),
                ('lattitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
    ]
