# Generated by Django 2.1.2 on 2018-10-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='floodTable',
        ),
        migrations.DeleteModel(
            name='rescueTable',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='flag',
        ),
    ]
