# Generated by Django 2.1.2 on 2018-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0012_auto_20181026_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='amenities',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='levelchange',
            field=models.CharField(default='Decreasing', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rescueHome',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rescuelevel',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='waterlevel',
            field=models.CharField(default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='feedback',
            field=models.CharField(default='No feedback', max_length=500),
        ),
    ]
