# Generated by Django 2.1.2 on 2018-10-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0014_auto_20181028_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='family',
            field=models.IntegerField(default=1),
        ),
    ]
