# Generated by Django 2.1.2 on 2018-10-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0015_auto_20181028_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='family',
            field=models.IntegerField(),
        ),
    ]
