# Generated by Django 2.1.2 on 2018-10-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0016_auto_20181028_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bedsno',
            field=models.CharField(default='100', max_length=4),
        ),
    ]
